repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-case-conflict
    -   id: check-illegal-windows-names

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix --select I ]
    # Run the formatter.
    - id: ruff-format

# -   repo: local
#     hooks:
#     -   id: ruff-linter-with-isort
#         name: ruff lint with isort
#         entry: ruff check --select I --fix .
#         language: system
#         types: [python]
#         stages: [commit]

#     -   id: ruff-format
#         name: ruff format
#         entry: ruff format .
#         language: system
#         types: [python]
#         stages: [commit]

    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true
