[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "readwise-sqlalchemy"
version = "0.1.0"
dependencies = [
    "rich",
    "mypy",
    "pytest",
    "requests",
    "ruff",
]

[project.scripts]
rw = "readwise_sqlalchemy.main:main"
