name: Default CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build package (wheel & sdist)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          if-no-files-found: error
          path: dist/

      - name: Show built artifacts
        run: ls -l dist/

  test:
    name: Test on Python ${{ matrix.python-version }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Show build artifacts again
        run: ls -l build-artifacts/

      - name: Install built package (wheel preferred)
        run: |
          pip install dist/*.whl || pip install dist/*.tar.gz

      - name: Install dev dependencies
        run: pip install ".[dev]"

      - name: Create mock .env file
        run: |
          mkdir -p $HOME/.config/readwise-local-plus/
          echo "READWISE_API_TOKEN=abc123" > $HOME/.config/readwise-local-plus/.env
          cat $HOME/.config/readwise-local-plus/.env

      - name: Run ruff
        run: ruff check

      - name: Check ruff formatting (dry-run)
        run: ruff format --diff

      - name: Run mypy (strict)
        run: mypy readwise_local_plus --strict --config-file=pyproject.toml

      - name: Run pytest
        run: pytest

      - name: Run CLI help
        run: rwlp --help

      - name: Show installed files (for debugging)
        run: pip show -f readwise-local-plus

      - name: Run pytest-cov
        run: pytest --cov=readwise_local_plus tests/
