name: Default

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        install-method: ["wheel", "sdist"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      if: matrix.install-method == 'wheel' || matrix.install-method == 'sdist'
      run: python -m build

    - name: Install the package
      run: |
        if [[ "${{ matrix.install-method }}" == "wheel" ]]; then
          pip install dist/*.whl
        else
          pip install dist/*.tar.gz
        fi

    - name: Run ruff
      run: ruff check

    - name: Run ruff format
      run: ruff format --diff

    - name: Run pytest
      run: pytest

    # TODO: See #2: Run CLI help in GitHub action
    # - name: Run ldm --help
    #   run: ldm --help

    - name: List installed package files for debugging
      run: |
        pip show -f readwise_sqlalchemy